### ISSUE TITLE
PeptideBuilder does not build the last oxygen

### ISSUE THREAD

**Issue by kad-ecoli** [clauswilke/PeptideBuilder#8]
The last amino acid of a peptide chain usually has an extra oxygen atom " OXT" as the last backbone atom. Any chance PeptideBuilder can build that?

**Comment by KirillShmilovich** [comment]
Hello! Thank you so much for putting together this library -- I've found it very helpful in my work.


> The last amino acid of a peptide chain usually has an extra oxygen atom " OXT" as the last backbone atom. Any chance PeptideBuilder can build that?
> Addressing this issue is low on my priority list but I'm happy to consider a pull request that implements this feature.

Regarding this point, is this a feature that you expect will be implemented? If not, could you perhaps provide some guidance into how I could go about building the terminal carboxyl group? 

Thanks!

**Comment by clauswilke** [comment]
> Regarding this point, is this a feature that you expect will be implemented? If not, could you perhaps provide some guidance into how I could go about building the terminal carboxyl group?

Sorry, no, the original authors have moved on to different topics and this is low priority for us. We just try to make sure the software continues to exist and runs with the latest libraries.

To implement this feature, you'd just have to write a function that places the appropriate atoms into the appropriate position in space. You can see how the code does this for other atoms and then mirror that existing code. The entire library is only a few hundred lines of code, mostly quite repetitive, so it shouldn't be too hard to figure out how it works.

**Comment by clauswilke** [comment]
This is now possible and will be part of the upcoming v1.1 release.

https://github.com/clauswilke/PeptideBuilder/blob/973e1302590c4eaacf50b2372d4cace2bdfbbee3/examples/simpleExample.py#L11-L19
